const UPDATE_CONDITION = "UPDATE_CONDITION";
const ADD_CONDITION = "ADD_CONDITION";
const DELETE_CONDITION = "DELETE_CONDITION";

const UPDATE_PROCEDURE = "UPDATE_PROCEDURE";
const ADD_PROCEDURE = "ADD_PROCEDURE";
const DELETE_PROCEDURE = "DELETE_PROCEDURE";

const UPDATE_ENCOUNTER = "UPDATE_ENCOUNTER";
const ADD_ENCOUNTER = "ADD_ENCOUNTER";
const DELETE_ENCOUNTER = "DELETE_ENCOUNTER";

const UPDATE_ALLERGY_INTOLERANCE = "UPDATE_ALLERGY_INTOLERANCE";
const ADD_ALLERGY_INTOLERANCE = "ADD_ALLERGY_INTOLERANCE";
const DELETE_ALLERGY_INTOLERANCE = "DELETE_ALLERGY_INTOLERANCE";

const UPDATE_FAMILY_MEMBER_HISTORY = "UPDATE_FAMILY_HISTORY";
const ADD_FAMILY_MEMBER_HISTORY = "ADD_FAMILY_MEMBER_HISTORY";
const DELETE_FAMILY_MEMBER_HISTORY = "DELETE_FAMILY_MEMBER_HISTORY";

const UPDATE_MEDICATION_STATEMENT = "UPDATE_MEDICATION_STATEMENT";
const ADD_MEDICATION_STATEMENT = "ADD_MEDICATION_STATEMENT";
const DELETE_MEDICATION_STATEMENT = "DELETE_MEDICATION_STATEMENT";

const UPDATE_OBSERVATION = "UPDATE_OBSERVATION";
const ADD_OBSEVATION = "ADD_OBSEVATION";
const DELETE_OBSERVATION = "DELETE_OBSERVATION";

const UPDATE_ADVERSE_EVENT = "UPDATE_ADVERSE_EVENT";
const ADD_ADVERSE_EVENT = "ADD_ADVERSE_EVENT";
const DELETE_ADVERSE_EVENT = "DELETE_ADVERSE_EVENT";

const UPDATE_SOCIAL_HISTORY = "UPDATE_SOCIAL_HISTORY";
const ADD_SOCIAL_HISTORY = "ADD_SOCIAL_HISTORY";
const DELETE_SOCIAL_HISTORY = "DELETE_SOCIAL_HISTORY";

const UPDATE_IMMUNIZATION = "UPDATE_IMMUNIZATION";
const ADD_IMMUNIZATION = "ADD_IMMUNIZATION";
const DELETE_IMMUNIZATION = "DELETE_IMMUNIZATION";
export {
  UPDATE_CONDITION,
  ADD_CONDITION,
  DELETE_CONDITION,
  UPDATE_PROCEDURE,
  ADD_PROCEDURE,
  DELETE_PROCEDURE,
  UPDATE_ENCOUNTER,
  ADD_ENCOUNTER,
  DELETE_ENCOUNTER,
  UPDATE_ALLERGY_INTOLERANCE,
  ADD_ALLERGY_INTOLERANCE,
  DELETE_ALLERGY_INTOLERANCE,
  UPDATE_FAMILY_MEMBER_HISTORY,
  ADD_FAMILY_MEMBER_HISTORY,
  DELETE_FAMILY_MEMBER_HISTORY,
  UPDATE_MEDICATION_STATEMENT,
  ADD_MEDICATION_STATEMENT,
  DELETE_MEDICATION_STATEMENT,
  UPDATE_OBSERVATION,
  ADD_OBSEVATION,
  DELETE_OBSERVATION,
  UPDATE_ADVERSE_EVENT,
  ADD_ADVERSE_EVENT,
  DELETE_ADVERSE_EVENT,
  UPDATE_SOCIAL_HISTORY,
  ADD_SOCIAL_HISTORY,
  DELETE_SOCIAL_HISTORY,
  UPDATE_IMMUNIZATION,
  ADD_IMMUNIZATION,
  DELETE_IMMUNIZATION,
};
