export const conditionDictionary = [
  {
    value: "J06",
    arDisplay: "عدوى الجهاز التنفسي العلوي",
    display: "Upper Respiratory Tract Infection",
  },
  { value: "I10", arDisplay: "ارتفاع ضغط الدم", display: "Hypertension" },
  {
    value: "F43",
    arDisplay: "اضطراب عاطفي معتدل إلى شديد",
    display: "Moderate to Severe Emotional Disorder",
  },
  { value: "Z00.0", arDisplay: "العناية بالأسنان", display: "Dental Care" },
  {
    value: "K20-K31",
    arDisplay: "مشكلة في الجهاز الهضمي",
    display: "Gastrointestinal Problem",
  },
  { value: "E11", arDisplay: "داء السكري", display: "Diabetes Mellitus" },
  { value: "G40", arDisplay: "الصرع / نوبات", display: "Epilepsy / Seizures" },
  { value: "Z41.2", arDisplay: "استخراجات الأسنان", display: "Dental Extractions" },
  { value: "N39.0", arDisplay: "عدوى المسالك البولية", display: "Urinary Tract Infection" },
  { value: "J45", arDisplay: "ربو قصبي", display: "Bronchial Asthma" },
  {
    value: "F20-F29",
    arDisplay: "الذهان (بما في ذلك اضطراب ثنائي القطب)",
    display: "Psychosis (Including Bipolar Disorder)",
  },
  { value: "D50", arDisplay: "فقر الدم", display: "Anemia" },
  { value: "E05", arDisplay: "فرط نشاط الغدة الدرقية", display: "Hyperthyroidism" },
  {
    value: "F70-F79",
    arDisplay: "الإعاقة الذهنية واضطرابات النمو",
    display: "Intellectual Disability and Developmental Disorders",
  },
  { value: "B76", arDisplay: "الديدان", display: "Worms" },
  { value: "E03", arDisplay: "قصور الغدة الدرقية", display: "Hypothyroidism" },
  {
    value: "F45",
    arDisplay: "شكاوى جسدية غير مفسرة طبياً",
    display: "Medically Unexplained Somatic Complaints",
  },
  { value: "A09", arDisplay: "إسهال", display: "Diarrhea" },
  {
    value: "I64",
    arDisplay: "حوادث الأوعية الدموية (السكتة الدماغية)",
    display: "Vascular Accidents (Stroke)",
  },
  { value: "F84.0", arDisplay: "التوحد", display: "Autism" },
  {
    value: "V01-V99",
    arDisplay: "حوادث السيارات، الدراجات النارية، إلخ.",
    display: "Vehicle Accidents, Motorcycles, etc.",
  },
  { value: "F90", arDisplay: "أطفال مفرطون في النشاط", display: "Hyperactive Children" },
  { value: "K29", arDisplay: "التهاب المعدة والأمعاء", display: "Gastritis and Enteritis" },
  { value: "Icterus", arDisplay: "متلازمة الصفراء الحادة", display: "Acute Jaundice Syndrome" },
  { value: "B01", arDisplay: "جدري الماء", display: "Chickenpox" },
  { value: "B86", arDisplay: "الجرب", display: "Scabies" },
  { value: "H10", arDisplay: "التهاب الملتحمة", display: "Conjunctivitis" },
  { value: "M06", arDisplay: "التهاب المفاصل الروماتويدي", display: "Rheumatoid Arthritis" },
  {
    value: "J18",
    arDisplay: "عدوى الجهاز التنفسي السفلي",
    display: "Lower Respiratory Tract Infection",
  },
  { value: "H65", arDisplay: "التهاب الأذن الوسطى", display: "Otitis Media" },
  { value: "H75", arDisplay: "التهاب الأذن الداخلية", display: "Inner Ear Inflammation" },
  { value: "A00", arDisplay: "الكوليرا", display: "Cholera" },
  {
    value: "A02",
    arDisplay: "عدوى السالمونيلا الأخرى",
    display: "Other Salmonella Infections",
  },
  { value: "A03", arDisplay: "الشيغيلات", display: "Shigellosis" },
  { value: "A06", arDisplay: "الأميبيات", display: "Amoebiasis" },
  {
    value: "B00",
    arDisplay: "عدوى فيروس الهربس [الهربس البسيط]",
    display: "Herpes Simplex Virus Infection",
  },
  {
    value: "B20",
    arDisplay: "مرض الإيدز الناتج عن الأمراض المعدية والطفيلية",
    display: "AIDS Due to Infectious and Parasitic Diseases",
  },
  {
    value: "B82",
    arDisplay: "طفيليات معوية غير محددة",
    display: "Unspecified Intestinal Parasites",
  },
  {
    value: "E46",
    arDisplay: "سوء التغذية البروتيني الطاقي",
    display: "Protein-Energy Malnutrition",
  },
  { value: "E86", arDisplay: "نقص الحجم", display: "Hypovolemia" },
  {
    value: "J13",
    arDisplay: "الالتهاب الرئوي بسبب المكورات الرئوية",
    display: "Pneumococcal Pneumonia",
  },
  {
    value: "J15",
    arDisplay: "التهاب الرئة البكتيري، غير مصنف في مكان آخر",
    display: "Bacterial Pneumonia, Not Elsewhere Classified",
  },
  { value: "K02", arDisplay: "تسوس الأسنان", display: "Dental Caries" },
  { value: "K28", arDisplay: "قرحة المعدة اللفائفية", display: "Duodenal Ulcer" },
  { value: "K30", arDisplay: "عسر الهضم", display: "Indigestion" },
  {
    value: "K52",
    arDisplay: "التهاب المعدة والقولون غير المعدي الأخر",
    display: "Noninfectious Gastritis and Colitis",
  },
  {
    value: "K59",
    arDisplay: "اضطرابات الأمعاء الوظيفية الأخرى",
    display: "Other Functional Intestinal Disorders",
  },
  { value: "L03", arDisplay: "التهاب النسيج الخلوي", display: "Cellulitis" },
  { value: "L30", arDisplay: "التهاب الجلد الآخر", display: "Other Dermatitis" },
  { value: "N39", arDisplay: "اضطرابات الجهاز البولي", display: "Urinary System Disorders" },
  {
    value: "O80",
    arDisplay: "لقاء للتسليم الكامل الأجل غير المعقد",
    display: "Full-Term Uncomplicated Delivery",
  },
  { value: "T14", arDisplay: "إصابة غير محددة", display: "Unspecified Injury" },
  {
    value: "Z59",
    arDisplay: "المشاكل المتعلقة بالسكن والظروف الاقتصادية",
    display: "Housing and Economic Problems",
  },
  {
    value: "Z60",
    arDisplay: "المشاكل المتعلقة بالبيئة الاجتماعية",
    display: "Social Environment Problems",
  },
  {
    value: "B02",
    arDisplay: "الحزام الناري [هربس زوستر]",
    display: "Shingles [Herpes Zoster]",
  },
  {
    value: "B18",
    arDisplay: "التهاب الكبد الفيروسي المزمن",
    display: "Chronic Viral Hepatitis",
  },
  { value: "C53", arDisplay: "الورم الخبيث لعنق الرحم", display: "Malignant Cervical Tumor" },
  { value: "D50", arDisplay: "فقر الدم بنقص الحديد", display: "Iron Deficiency Anemia" },
  { value: "E03", arDisplay: "قصور الغدة الدرقية الأخر", display: "Other Hypothyroidism" },
  { value: "E55", arDisplay: "نقص فيتامين د", display: "Vitamin D Deficiency" },
  { value: "F32", arDisplay: "اضطراب الاكتئاب الرئيسي", display: "Major Depressive Disorder" },
  { value: "G40", arDisplay: "الصرع", display: "Epilepsy" },
  { value: "H10", arDisplay: "التهاب الملتحمة", display: "Conjunctivitis" },
  { value: "I10", arDisplay: "ارتفاع ضغط الدم الأساسي", display: "Primary Hypertension" },
  { value: "I20", arDisplay: "الذبحة الصدرية", display: "Angina Pectoris" },
  {
    value: "I25",
    arDisplay: "مرض القلب الإقفاري المزمن",
    display: "Chronic Ischemic Heart Disease",
  },
  {
    value: "J06",
    arDisplay: "العدوى الحادة للجهاز التنفسي العلوي",
    display: "Acute Upper Respiratory Tract Infection",
  },
  { value: "L20", arDisplay: "التهاب الجلد التأتبي", display: "Atopic Dermatitis" },
  { value: "L50", arDisplay: "الشرى", display: "Urticaria" },
  {
    value: "M05",
    arDisplay: "التهاب المفاصل الروماتويدي مع عامل روماتويدي",
    display: "Rheumatoid Arthritis with Rheumatoid Factor",
  },
  { value: "M54", arDisplay: "ألم الظهر", display: "Back Pain" },
  {
    value: "N10",
    arDisplay: "التهاب الكلى الأنبوبي الكلوي الحاد",
    display: "Acute Tubulointerstitial Nephritis",
  },
  { value: "N17", arDisplay: "الفشل الكلوي الحاد", display: "Acute Renal Failure" },
  { value: "O15", arDisplay: "تسمم الحمل", display: "Eclampsia" },
  {
    value: "P03",
    arDisplay: "المولود الجديد المتأثر بمضاعفات المشيمة والحبل السري والأغشية",
    display: "Newborn Affected by Placenta, Cord, and Membrane Complications",
  },
  {
    value: "Q00",
    arDisplay: "عدم تكون الدماغ وتشوهات مماثلة",
    display: "Anencephaly and Similar Malformations",
  },
  { value: "R50", arDisplay: "الحمى", display: "Fever" },
  { value: "S05", arDisplay: "إصابة العين والمدار", display: "Injury of Eye and Orbit" },
  { value: "T74", arDisplay: "متلازمات سوء المعاملة", display: "Abuse Syndromes" },
  { value: "U07", arDisplay: "كوفيد-19", display: "COVID-19" },
  {
    value: "V01",
    arDisplay: "المشاة المصابون في تصادم مع دراجة هوائية",
    display: "Pedestrian Injured in Collision with Bicycle",
  },
  {
    value: "X00",
    arDisplay: "التعرض لحريق غير مسيطر عليه في مبنى أو هيكل",
    display: "Exposure to Uncontrolled Fire in Building or Structure",
  },
  {
    value: "Z62",
    arDisplay: "المشاكل المتعلقة بالتربية",
    display: "Problems Related to Upbringing",
  },
  {
    value: "Z71",
    arDisplay:
      "الأشخاص الذين يلجأون إلى الخدمات الصحية للتشاور والنصائح الطبية، غير مصنفة في مكان آخر",
    display:
      "People Seeking Health Services for Consultation and Medical Advice, Not Classified Elsewhere",
  },
  { value: "Z72", arDisplay: "المشاكل المتعلقة بأسلوب الحياة", display: "Lifestyle Problems" },
  {
    value: "Z74",
    arDisplay: "المشاكل المتعلقة بالاعتماد على الآلات والأجهزة المساعدة",
    display: "Problems Related to Dependence on Machines and Assistive Devices",
  },
  { value: "A20", arDisplay: "الطاعون", display: "Plague" },
  {
    value: "A28",
    arDisplay: "أمراض بكتيرية حيوانية المصدر أخرى، غير مصنفة في مكان آخر",
    display: "Other Zoonotic Bacterial Diseases, Not Elsewhere Classified",
  },
  { value: "B03", arDisplay: "جدري", display: "Smallpox" },
  { value: "B17", arDisplay: "التهاب الكبد سي الحاد", display: "Acute Hepatitis C" },
  { value: "C16", arDisplay: "الورم الخبيث في المعدة", display: "Malignant Gastric Tumor" },
  { value: "C91", arDisplay: "لوكيميا لمفاوية حادة", display: "Acute Lymphocytic Leukemia" },
  { value: "D73", arDisplay: "أمراض الطحال", display: "Diseases of the Spleen" },
  {
    value: "E02",
    arDisplay: "قصور الغدة الدرقية الناجم عن نقص اليود دون أعراض",
    display: "Asymptomatic Hypothyroidism Due to Iodine Deficiency",
  },
  {
    value: "E44",
    arDisplay: "سوء التغذية البروتيني من الدرجة المعتدلة والخفيفة",
    display: "Moderate and Mild Protein-Energy Malnutrition",
  },
  { value: "F24", arDisplay: "اضطراب نفسي مشترك", display: "Shared Psychotic Disorder" },
  { value: "G51", arDisplay: "شلل بيل", display: "Bell's Palsy" },
  {
    value: "H65",
    arDisplay: "التهاب الأذن الوسطى غير القيحي",
    display: "Non-Suppurative Otitis Media",
  },
  { value: "I42", arDisplay: "اعتلال عضلة القلب", display: "Cardiomyopathy" },
  { value: "J20", arDisplay: "القصبات الهوائية الحادة", display: "Acute Bronchitis" },
  {
    value: "K05",
    arDisplay: "التهاب اللثة وأمراض الفم",
    display: "Gingivitis and Oral Diseases",
  },
  {
    value: "K12",
    arDisplay: "التهاب الفم والآفات المرتبطة به",
    display: "Stomatitis and Related Lesions",
  },
  { value: "L03", arDisplay: "التهاب النسيج الخلوي", display: "Cellulitis" },
  { value: "M25", arDisplay: "ألم المفصل", display: "Joint Pain" },
  {
    value: "N41",
    arDisplay: "الأمراض الالتهابية للبروستات",
    display: "Inflammatory Diseases of the Prostate",
  },
  {
    value: "N76",
    arDisplay: "التهابات أخرى في المهبل والفرج",
    display: "Other Vaginal and Vulval Infections",
  },
  {
    value: "O14",
    arDisplay: "ارتفاع ضغط الدم الناتج عن الحمل",
    display: "Pregnancy-Induced Hypertension",
  },
  {
    value: "P01",
    arDisplay: "اضطرابات الوليد المرتبطة بقصر مدة الحمل وانخفاض وزن الولادة",
    display: "Neonatal Disorders Related to Short Gestation and Low Birth Weight",
  },
  { value: "R05", arDisplay: "السعال", display: "Cough" },
  { value: "R55", arDisplay: "الإغماء والانهيار", display: "Syncope and Collapse" },
  { value: "S06", arDisplay: "إصابة داخل الجمجمة", display: "Intracranial Injury" },
  {
    value: "T36",
    arDisplay: "التسمم بالمضادات الحيوية الجهازية",
    display: "Poisoning by Systemic Antibiotics",
  },
  {
    value: "Z73",
    arDisplay: "المشاكل المتعلقة بصعوبة إدارة الحياة",
    display: "Problems Related to Life Management Difficulty",
  },
];

export const procedureDictionary = [
  { value: "104001", arDisplay: "استئصال آفة الرضفة", display: "Excision of Patellar Lesion" },
  {
    value: "115006",
    arDisplay: "تركيب جهاز تقويم أسنان قابل للإزالة",
    display: "Placement of Removable Orthodontic Appliance",
  },
  {
    value: "119000",
    arDisplay: "استئصال الفص الجزئي الرئوي عبر التنظير الصدري",
    display: "Thoracoscopic Partial Lobectomy",
  },
  {
    value: "121005",
    arDisplay: "حقن علاج خلف مقلة العين",
    display: "Injection Treatment Behind Eyeball",
  },
  {
    value: "128004",
    arDisplay: "فحص جلد بواسطة مجهر يدوي",
    display: "Skin Examination with Hand Microscope",
  },
  {
    value: "133000",
    arDisplay: "غرس القسطرة العصبية في العصبون العضلي عن طريق الجلد",
    display: "Implantation of Neurocatheter into Neuromuscular Junction via Percutaneous Route",
  },
  {
    value: "135007",
    arDisplay: "بضع مفصل الرسغ مع استكشاف وخزعة",
    display: "Wrist Arthrotomy with Exploration and Biopsy",
  },
  {
    value: "142007",
    arDisplay: "استئصال ورم من منطقة الكتف، عميق، عضلي",
    display: "Excision of Tumor from Shoulder Area, Deep, Muscular",
  },
  {
    value: "146005",
    arDisplay: "إصلاح عدم التئام مشط القدم مع طعم عظمي",
    display: "Repair of Metatarsal Nonunion with Bone Graft",
  },
  {
    value: "153001",
    arDisplay: "تنظير المثانة والإحليل مع استئصال القيلة الحالبية",
    display: "Cystourethroscopy with Excision of Ureterocele",
  },
  {
    value: "160007",
    arDisplay: "إزالة جسم غريب من الوتر و/أو غمد الوتر",
    display: "Removal of Foreign Body from Tendon and/or Tendon Sheath",
  },
  { value: "166001", arDisplay: "العلاج السلوكي", display: "Behavioral Therapy" },
  {
    value: "170009",
    arDisplay: "اختبار قرص الفاعلية الخاص، فحص الفانكومايسين",
    display: "Special Potency Disk Test, Vancomycin Test",
  },
  {
    value: "174000",
    arDisplay: "عملية هاريسون-ريتشاردسون على المهبل",
    display: "Harrison-Richardson Operation on Vagina",
  },
  { value: "176003", arDisplay: "مفاغرة المستقيم", display: "Rectal Anastomosis" },
  {
    value: "189009",
    arDisplay: "استئصال آفة من الشريان",
    display: "Excision of Lesion from Artery",
  },
  {
    value: "197002",
    arDisplay: "اختبار التحول من العفن إلى الخميرة",
    display: "Mold to Yeast Conversion Test",
  },
  {
    value: "230009",
    arDisplay: "عملية ميلر، تعليق الإحليل والمثانة",
    display: "Miller Procedure, Urethral and Bladder Suspension",
  },
  {
    value: "243009",
    arDisplay: "استبدال أنبوب البطين الدماغي",
    display: "Replacement of Brain Ventricular Tube",
  },
  { value: "245002", arDisplay: "قطع العقدة العصبية", display: "Neurectomy" },
  {
    value: "262007",
    arDisplay: "شفط حوض الكلى عن طريق الجلد",
    display: "Percutaneous Nephric Pelvis Aspiration",
  },
  {
    value: "267001",
    arDisplay: "استئصال ناسور الشرج، متعدد",
    display: "Excision of Anal Fistula, Multiple",
  },
];

export const encounterDictionary = [
  { value: "AMB", arDisplay: "عيادات خارجية", display: "Outpatient Clinics" },
  { value: "EMER", arDisplay: "طوارئ", display: "Emergency" },
  { value: "IMP", arDisplay: "مريض داخلي", display: "Inpatient" },
  { value: "SS", arDisplay: "إقامة قصيرة", display: "Short Stay" },
];

export const allergyIntoleranceDictionary = [
  {
    value: "J30.1",
    arDisplay: "التهاب الأنف التحسسي بسبب حبوب اللقاح",
    display: "Allergic Rhinitis due to Pollen",
  },
  {
    value: "J30.2",
    arDisplay: "التهاب الأنف التحسسي الموسمي الآخر",
    display: "Other Seasonal Allergic Rhinitis",
  },
  {
    value: "J30.81",
    arDisplay: "التهاب الأنف التحسسي بسبب قشور الحيوانات",
    display: "Allergic Rhinitis due to Animal Dander",
  },
  {
    value: "J30.89",
    arDisplay: "التهاب الأنف التحسسي الآخر",
    display: "Other Allergic Rhinitis",
  },
  {
    value: "L23.0",
    arDisplay: "التهاب الجلد التماسي التحسسي بسبب المعادن",
    display: "Allergic Contact Dermatitis due to Metals",
  },
  {
    value: "L23.6",
    arDisplay: "التهاب الجلد التماسي التحسسي بسبب مستحضرات التجميل",
    display: "Allergic Contact Dermatitis due to Cosmetics",
  },
  {
    value: "L23.7",
    arDisplay: "التهاب الجلد التماسي التحسسي بسبب النباتات",
    display: "Allergic Contact Dermatitis due to Plants",
  },
  {
    value: "L23.81",
    arDisplay: "التهاب الجلد التماسي التحسسي بسبب الحيوانات",
    display: "Allergic Contact Dermatitis due to Animals",
  },
  {
    value: "L23.9",
    arDisplay: "التهاب الجلد التماسي التحسسي غير محدد",
    display: "Unspecified Allergic Contact Dermatitis",
  },
  {
    value: "L24.7",
    arDisplay: "التهاب الجلد التماسي المزعج بسبب النباتات",
    display: "Irritant Contact Dermatitis due to Plants",
  },
  { value: "L50.0", arDisplay: "شرى تحسسي", display: "Allergic Urticaria" },
  { value: "L50.9", arDisplay: "شرى غير محدد", display: "Unspecified Urticaria" },
  {
    value: "T78.0",
    arDisplay: "صدمة تأقية بسبب رد فعل غذائي سيئ",
    display: "Anaphylactic Shock due to Adverse Food Reaction",
  },
  {
    value: "T78.01",
    arDisplay: "رد فعل تأقي بسبب الفول السوداني",
    display: "Anaphylactic Reaction due to Peanuts",
  },
  {
    value: "T78.02",
    arDisplay: "رد فعل تأقي بسبب المأكولات البحرية",
    display: "Anaphylactic Reaction due to Seafood",
  },
  {
    value: "T78.1",
    arDisplay: "ردود فعل غذائية سيئة أخرى",
    display: "Other Adverse Food Reactions",
  },
  {
    value: "T78.2",
    arDisplay: "صدمة تأقية غير محددة",
    display: "Unspecified Anaphylactic Shock",
  },
  { value: "T78.3", arDisplay: "وذمة وعائية", display: "Angioedema" },
  { value: "T78.4", arDisplay: "حساسية غير محددة", display: "Unspecified Allergy" },
  {
    value: "T88.6",
    arDisplay: "صدمة تأقية بسبب تأثير سيئ لدواء صحيح",
    display: "Anaphylactic Shock due to Correct Drug Usage",
  },
  {
    value: "T88.7",
    arDisplay: "صدمة تأقية بسبب مصل",
    display: "Anaphylactic Shock due to Serum",
  },
  {
    value: "T88.8",
    arDisplay: "مضاعفات أخرى محددة للتحصين",
    display: "Other Specified Immunization Complications",
  },
  {
    value: "V15.05",
    arDisplay: "حساسية لوسائط التباين الإشعاعي",
    display: "Allergy to Radiographic Contrast Media",
  },
  { value: "V15.06", arDisplay: "حساسية للاتكس", display: "Allergy to Latex" },
  { value: "V15.07", arDisplay: "حساسية للدغات الحشرات", display: "Allergy to Insect Bites" },
  { value: "Z88.0", arDisplay: "حساسية للبنسلين", display: "Allergy to Penicillin" },
  {
    value: "Z88.1",
    arDisplay: "حساسية لمضادات حيوية أخرى",
    display: "Allergy to Other Antibiotics",
  },
  { value: "Z88.2", arDisplay: "حساسية للسلفوناميدات", display: "Allergy to Sulfonamides" },
  {
    value: "Z88.3",
    arDisplay: "حساسية لعوامل مضادة للعدوى أخرى",
    display: "Allergy to Other Anti-Infective Agents",
  },
  { value: "Z88.4", arDisplay: "حساسية لعوامل التخدير", display: "Allergy to Anesthetics" },
  {
    value: "Z88.5",
    arDisplay: "حساسية للمواد المخدرة",
    display: "Allergy to Narcotic Substances",
  },
  { value: "Z88.6", arDisplay: "حساسية لعوامل مسكنة", display: "Allergy to Analgesic Agents" },
  {
    value: "Z88.7",
    arDisplay: "حساسية للمصل واللقاح",
    display: "Allergy to Serum and Vaccine",
  },
  {
    value: "Z88.8",
    arDisplay: "حساسية لأدوية وعقاقير ومواد بيولوجية أخرى",
    display: "Allergy to Other Drugs and Biological Substances",
  },
  {
    value: "Z88.9",
    arDisplay: "حساسية لأدوية وعقاقير ومواد بيولوجية غير محددة",
    display: "Allergy to Unspecified Drugs and Biological Substances",
  },
  { value: "Z91.010", arDisplay: "حساسية للفول السوداني", display: "Peanut Allergy" },
  { value: "Z91.011", arDisplay: "حساسية لمنتجات الألبان", display: "Dairy Allergy" },
  { value: "Z91.012", arDisplay: "حساسية للبيض", display: "Egg Allergy" },
  { value: "Z91.013", arDisplay: "حساسية للمكسرات", display: "Nut Allergy" },
  { value: "Z91.014", arDisplay: "حساسية للمأكولات البحرية", display: "Seafood Allergy" },
];

export const familyHistoryDictionary = [
  { value: "127940007", arDisplay: "والد/والدة", display: "Parent" },
  { value: "126830008", arDisplay: "شقيق/شقيقة", display: "Sibling" },
  { value: "127850005", arDisplay: "طفل/طفلة", display: "Child" },
  { value: "127930003", arDisplay: "جد/جدة من جهة الأم", display: "Maternal Grandparent" },
  { value: "127920004", arDisplay: "جد/جدة من جهة الأب", display: "Paternal Grandparent" },
  { value: "127910009", arDisplay: "عمة", display: "Aunt (Paternal)" },
  { value: "127900000", arDisplay: "خالة", display: "Aunt (Maternal)" },
  { value: "127890008", arDisplay: "خال", display: "Uncle (Maternal)" },
  { value: "127880007", arDisplay: "عم", display: "Uncle (Paternal)" },
  { value: "127870003", arDisplay: "ابن عم/ابن خال", display: "Male Cousin" },
  { value: "127860009", arDisplay: "ابنة عم/ابنة خال", display: "Female Cousin" },
  { value: "429000000", arDisplay: "والد/والدة زوج أو زوجة", display: "Parent-in-Law" },
  { value: "428900009", arDisplay: "أخ/أخت زوج أو زوجة", display: "Sibling-in-Law" },
  { value: "428800004", arDisplay: "ابن/ابنة زوج أو زوجة", display: "Stepchild" },
  { value: "128100014", arDisplay: "أب", display: "Father" },
  { value: "128080000", arDisplay: "أم", display: "Mother" },
  { value: "309090004", arDisplay: "أخ غير شقيق/أخت غير شقيقة", display: "Half-Sibling" },
  { value: "407940001", arDisplay: "حما", display: "Father-in-Law" },
  { value: "407950000", arDisplay: "حماة", display: "Mother-in-Law" },
  { value: "427900006", arDisplay: "صهر", display: "Brother-in-Law" },
  { value: "407930006", arDisplay: "كنة", display: "Daughter-in-Law" },
  {
    value: "427920001",
    arDisplay: "أخو زوج/أخو زوجة",
    display: "Brother-in-Law (Husband's Brother/Wife's Brother)",
  },
  {
    value: "427910006",
    arDisplay: "أخت زوج/أخت زوجة",
    display: "Sister-in-Law (Husband's Sister/Wife's Sister)",
  },
  { value: "127840000", arDisplay: "والد حاضن/والدة حاضنة", display: "Foster Parent" },
  { value: "127830001", arDisplay: "طفل حاضن/طفلة حاضنة", display: "Foster Child" },
  { value: "128000009", arDisplay: "والد/والدة بالتبني", display: "Adoptive Parent" },
  { value: "127990001", arDisplay: "طفل بالتبني/طفلة بالتبني", display: "Adoptive Child" },
];

export const medicationStatement = {
  status: {
    description:
      "A code representing the patient or other source's judgment about the state of the medication used by the patient.",
    code: [
      { id: 1, value: "Active", label: "يتم تناول الدواء حاليًا" },
      { id: 2, value: "Completed", label: "تم إنهاء أو إكمال الدواء" },
      { id: 3, value: "Entered-In-Error", label: "تم إنهاء أو إكمال الدواء" },
      {
        id: 4,
        value: "Intended",
        label: "الدواء مخصص ليتم تناوله ولكن لم يبدأ بعد",
      },
      { id: 5, value: "Stopped", label: "لم يعد يتم تناول الدواء" },
      { id: 6, value: "On-Hold", label: "الدواء قيد الانتظار" },
      { id: 7, value: "Unknown", label: "الحالة الحالية للدواء غير معروفة" },
    ],
  },
  taken: {
    description: "Indicates if the medication was taken as prescribed",
    options: {
      Y: "Yes, the medication was taken",
      N: "No, the medication was not taken",
      UNK: "Unknown if the medication was taken",
      NA: "Not applicable",
    },
  },
  category: {
    description: "The category of the medication statement",
    options: {
      Inpatient: "Medication taken during an inpatient encounter",
      Outpatient: "Medication taken during an outpatient encounter",
      Community: "Medication taken outside of healthcare encounters",
      Discharge: "Medication prescribed at discharge",
    },
  },
  reasonCode: {
    description: "The reason for the medication statement",
    reasonCode: {
      A09: "إسهال معدي",
      B20: "فيروس العوز المناعي البشري",
      C34: "سرطان الرئة",
      D50: "نقص الحديد",
      E11: "داء السكري 2",
      E66: "السمنة",
      F32: "الاكتئاب",
      G40: "الصرع",
      H10: "التهاب الملتحمة",
      I10: "ارتفاع الضغط",
      I20: "الذبحة الصدرية",
      I50: "قصور القلب",
      J06: "التنفسي العلوي",
      J18: "الالتهاب الرئوي",
      K29: "التهاب المعدة",
      L20: "إكزيما",
      M54: "ألم الظهر",
      N39: "التهاب المسالك البولية",
      O80: "الولادة الطبيعية",
      P03: "مضاعفات الولادة",
      Q00: "عدم تكون الدماغ",
      R10: "ألم بطني",
      R51: "صداع",
      S02: "كسر الجمجمة",
      T14: "إصابة",
      U07: "كوفيد-19",
      V01: "إصابة المشاة",
      W18: "سقوط",
      X00: "التعرض للحريق",
      Y35: "التدخل القانوني",
      Z00: "الفحص العام",
      Z04: "ملاحظة بعد الحادث",
      Z08: "متابعة بعد العلاج",
      Z12: "فحص السرطان",
      Z28: "التحصين غير المنفذ",
      Z30: "إدارة موانع الحمل",
      Z51: "الرعاية الطبية",
      Z71: "النصيحة الطبية",
      Z72: "مشاكل نمط الحياة",
      Z76: "الشخص الذي يلجأ للخدمات الصحية",
    },
  },
};

export const observationDictionary = [
  {
    value: "J06",
    arDisplay: "عدوى الجهاز التنفسي العلوي",
    display: "Upper Respiratory Tract Infection",
  },
  { value: "I10", arDisplay: "ارتفاع ضغط الدم", display: "Hypertension" },
  {
    value: "F43",
    arDisplay: "اضطراب عاطفي معتدل إلى شديد",
    display: "Moderate to Severe Emotional Disorder",
  },
  { value: "Z00.0", arDisplay: "العناية بالأسنان", display: "Dental Care" },
  {
    value: "K20-K31",
    arDisplay: "مشكلة في الجهاز الهضمي",
    display: "Gastrointestinal Problem",
  },
  { value: "E11", arDisplay: "داء السكري", display: "Diabetes Mellitus" },
  { value: "G40", arDisplay: "الصرع / نوبات", display: "Epilepsy / Seizures" },
  { value: "Z41.2", arDisplay: "استخراجات الأسنان", display: "Dental Extractions" },
  { value: "N39.0", arDisplay: "عدوى المسالك البولية", display: "Urinary Tract Infection" },
  { value: "J45", arDisplay: "ربو قصبي", display: "Bronchial Asthma" },
  {
    value: "F20-F29",
    arDisplay: "الذهان (بما في ذلك اضطراب ثنائي القطب)",
    display: "Psychosis (Including Bipolar Disorder)",
  },
  { value: "D50", arDisplay: "فقر الدم", display: "Anemia" },
  { value: "E05", arDisplay: "فرط نشاط الغدة الدرقية", display: "Hyperthyroidism" },
  {
    value: "F70-F79",
    arDisplay: "الإعاقة الذهنية واضطرابات النمو",
    display: "Intellectual Disability and Developmental Disorders",
  },
  { value: "B76", arDisplay: "الديدان", display: "Worms" },
  { value: "E03", arDisplay: "قصور الغدة الدرقية", display: "Hypothyroidism" },
  {
    value: "F45",
    arDisplay: "شكاوى جسدية غير مفسرة طبياً",
    display: "Medically Unexplained Somatic Complaints",
  },
  { value: "A09", arDisplay: "إسهال", display: "Diarrhea" },
  {
    value: "I64",
    arDisplay: "حوادث الأوعية الدموية (السكتة الدماغية)",
    display: "Vascular Accidents (Stroke)",
  },
  { value: "F84.0", arDisplay: "التوحد", display: "Autism" },
  {
    value: "V01-V99",
    arDisplay: "حوادث السيارات، الدراجات النارية، إلخ.",
    display: "Vehicle Accidents, Motorcycles, etc.",
  },
  { value: "F90", arDisplay: "أطفال مفرطون في النشاط", display: "Hyperactive Children" },
  { value: "K29", arDisplay: "التهاب المعدة والأمعاء", display: "Gastritis and Enteritis" },
  { value: "Icterus", arDisplay: "متلازمة الصفراء الحادة", display: "Acute Jaundice Syndrome" },
  { value: "B01", arDisplay: "جدري الماء", display: "Chickenpox" },
  { value: "B86", arDisplay: "الجرب", display: "Scabies" },
  { value: "H10", arDisplay: "التهاب الملتحمة", display: "Conjunctivitis" },
  { value: "M06", arDisplay: "التهاب المفاصل الروماتويدي", display: "Rheumatoid Arthritis" },
  {
    value: "J18",
    arDisplay: "عدوى الجهاز التنفسي السفلي",
    display: "Lower Respiratory Tract Infection",
  },
  { value: "H65", arDisplay: "التهاب الأذن الوسطى", display: "Otitis Media" },
  { value: "H75", arDisplay: "التهاب الأذن الداخلية", display: "Inner Ear Inflammation" },
  { value: "A00", arDisplay: "الكوليرا", display: "Cholera" },
  {
    value: "A02",
    arDisplay: "عدوى السالمونيلا الأخرى",
    display: "Other Salmonella Infections",
  },
  { value: "A03", arDisplay: "الشيغيلات", display: "Shigellosis" },
  { value: "A06", arDisplay: "الأميبيات", display: "Amoebiasis" },
  {
    value: "B00",
    arDisplay: "عدوى فيروس الهربس [الهربس البسيط]",
    display: "Herpes Simplex Virus Infection",
  },
  {
    value: "B20",
    arDisplay: "مرض الإيدز الناتج عن الأمراض المعدية والطفيلية",
    display: "AIDS Due to Infectious and Parasitic Diseases",
  },
  {
    value: "B82",
    arDisplay: "طفيليات معوية غير محددة",
    display: "Unspecified Intestinal Parasites",
  },
  {
    value: "E46",
    arDisplay: "سوء التغذية البروتيني الطاقي",
    display: "Protein-Energy Malnutrition",
  },
  { value: "E86", arDisplay: "نقص الحجم", display: "Hypovolemia" },
  {
    value: "J13",
    arDisplay: "الالتهاب الرئوي بسبب المكورات الرئوية",
    display: "Pneumococcal Pneumonia",
  },
  {
    value: "J15",
    arDisplay: "التهاب الرئة البكتيري، غير مصنف في مكان آخر",
    display: "Bacterial Pneumonia, Not Elsewhere Classified",
  },
  { value: "K02", arDisplay: "تسوس الأسنان", display: "Dental Caries" },
  { value: "K28", arDisplay: "قرحة المعدة اللفائفية", display: "Duodenal Ulcer" },
  { value: "K30", arDisplay: "عسر الهضم", display: "Indigestion" },
  {
    value: "K52",
    arDisplay: "التهاب المعدة والقولون غير المعدي الأخر",
    display: "Noninfectious Gastritis and Colitis",
  },
  {
    value: "K59",
    arDisplay: "اضطرابات الأمعاء الوظيفية الأخرى",
    display: "Other Functional Intestinal Disorders",
  },
  { value: "L03", arDisplay: "التهاب النسيج الخلوي", display: "Cellulitis" },
  { value: "L30", arDisplay: "التهاب الجلد الآخر", display: "Other Dermatitis" },
  { value: "N39", arDisplay: "اضطرابات الجهاز البولي", display: "Urinary System Disorders" },
  {
    value: "O80",
    arDisplay: "لقاء للتسليم الكامل الأجل غير المعقد",
    display: "Full-Term Uncomplicated Delivery",
  },
  { value: "T14", arDisplay: "إصابة غير محددة", display: "Unspecified Injury" },
  {
    value: "Z59",
    arDisplay: "المشاكل المتعلقة بالسكن والظروف الاقتصادية",
    display: "Housing and Economic Problems",
  },
  {
    value: "Z60",
    arDisplay: "المشاكل المتعلقة بالبيئة الاجتماعية",
    display: "Social Environment Problems",
  },
  {
    value: "B02",
    arDisplay: "الحزام الناري [هربس زوستر]",
    display: "Shingles [Herpes Zoster]",
  },
  {
    value: "B18",
    arDisplay: "التهاب الكبد الفيروسي المزمن",
    display: "Chronic Viral Hepatitis",
  },
  { value: "C53", arDisplay: "الورم الخبيث لعنق الرحم", display: "Malignant Cervical Tumor" },
  { value: "D50", arDisplay: "فقر الدم بنقص الحديد", display: "Iron Deficiency Anemia" },
  { value: "E03", arDisplay: "قصور الغدة الدرقية الأخر", display: "Other Hypothyroidism" },
  { value: "E55", arDisplay: "نقص فيتامين د", display: "Vitamin D Deficiency" },
  { value: "F32", arDisplay: "اضطراب الاكتئاب الرئيسي", display: "Major Depressive Disorder" },
  { value: "G40", arDisplay: "الصرع", display: "Epilepsy" },
  { value: "H10", arDisplay: "التهاب الملتحمة", display: "Conjunctivitis" },
  { value: "I10", arDisplay: "ارتفاع ضغط الدم الأساسي", display: "Primary Hypertension" },
  { value: "I20", arDisplay: "الذبحة الصدرية", display: "Angina Pectoris" },
  {
    value: "I25",
    arDisplay: "مرض القلب الإقفاري المزمن",
    display: "Chronic Ischemic Heart Disease",
  },
  {
    value: "J06",
    arDisplay: "العدوى الحادة للجهاز التنفسي العلوي",
    display: "Acute Upper Respiratory Tract Infection",
  },
  { value: "L20", arDisplay: "التهاب الجلد التأتبي", display: "Atopic Dermatitis" },
  { value: "L50", arDisplay: "الشرى", display: "Urticaria" },
  {
    value: "M05",
    arDisplay: "التهاب المفاصل الروماتويدي مع عامل روماتويدي",
    display: "Rheumatoid Arthritis with Rheumatoid Factor",
  },
  { value: "M54", arDisplay: "ألم الظهر", display: "Back Pain" },
  {
    value: "N10",
    arDisplay: "التهاب الكلى الأنبوبي الكلوي الحاد",
    display: "Acute Tubulointerstitial Nephritis",
  },
  { value: "N17", arDisplay: "الفشل الكلوي الحاد", display: "Acute Renal Failure" },
  { value: "O15", arDisplay: "تسمم الحمل", display: "Eclampsia" },
  {
    value: "P03",
    arDisplay: "المولود الجديد المتأثر بمضاعفات المشيمة والحبل السري والأغشية",
    display: "Newborn Affected by Placenta, Cord, and Membrane Complications",
  },
  {
    value: "Q00",
    arDisplay: "عدم تكون الدماغ وتشوهات مماثلة",
    display: "Anencephaly and Similar Malformations",
  },
  { value: "R50", arDisplay: "الحمى", display: "Fever" },
  { value: "S05", arDisplay: "إصابة العين والمدار", display: "Injury of Eye and Orbit" },
  { value: "T74", arDisplay: "متلازمات سوء المعاملة", display: "Abuse Syndromes" },
  { value: "U07", arDisplay: "كوفيد-19", display: "COVID-19" },
  {
    value: "V01",
    arDisplay: "المشاة المصابون في تصادم مع دراجة هوائية",
    display: "Pedestrian Injured in Collision with Bicycle",
  },
  {
    value: "X00",
    arDisplay: "التعرض لحريق غير مسيطر عليه في مبنى أو هيكل",
    display: "Exposure to Uncontrolled Fire in Building or Structure",
  },
  {
    value: "Z62",
    arDisplay: "المشاكل المتعلقة بالتربية",
    display: "Problems Related to Upbringing",
  },
  {
    value: "Z71",
    arDisplay:
      "الأشخاص الذين يلجأون إلى الخدمات الصحية للتشاور والنصائح الطبية، غير مصنفة في مكان آخر",
    display:
      "People Seeking Health Services for Consultation and Medical Advice, Not Classified Elsewhere",
  },
  { value: "Z72", arDisplay: "المشاكل المتعلقة بأسلوب الحياة", display: "Lifestyle Problems" },
  {
    value: "Z74",
    arDisplay: "المشاكل المتعلقة بالاعتماد على الآلات والأجهزة المساعدة",
    display: "Problems Related to Dependence on Machines and Assistive Devices",
  },
  { value: "A20", arDisplay: "الطاعون", display: "Plague" },
  {
    value: "A28",
    arDisplay: "أمراض بكتيرية حيوانية المصدر أخرى، غير مصنفة في مكان آخر",
    display: "Other Zoonotic Bacterial Diseases, Not Elsewhere Classified",
  },
  { value: "B03", arDisplay: "جدري", display: "Smallpox" },
  { value: "B17", arDisplay: "التهاب الكبد سي الحاد", display: "Acute Hepatitis C" },
  { value: "C16", arDisplay: "الورم الخبيث في المعدة", display: "Malignant Gastric Tumor" },
  { value: "C91", arDisplay: "لوكيميا لمفاوية حادة", display: "Acute Lymphocytic Leukemia" },
  { value: "D73", arDisplay: "أمراض الطحال", display: "Diseases of the Spleen" },
  {
    value: "E02",
    arDisplay: "قصور الغدة الدرقية الناجم عن نقص اليود دون أعراض",
    display: "Asymptomatic Hypothyroidism Due to Iodine Deficiency",
  },
  {
    value: "E44",
    arDisplay: "سوء التغذية البروتيني من الدرجة المعتدلة والخفيفة",
    display: "Moderate and Mild Protein-Energy Malnutrition",
  },
  { value: "F24", arDisplay: "اضطراب نفسي مشترك", display: "Shared Psychotic Disorder" },
  { value: "G51", arDisplay: "شلل بيل", display: "Bell's Palsy" },
  {
    value: "H65",
    arDisplay: "التهاب الأذن الوسطى غير القيحي",
    display: "Non-Suppurative Otitis Media",
  },
  { value: "I42", arDisplay: "اعتلال عضلة القلب", display: "Cardiomyopathy" },
  { value: "J20", arDisplay: "القصبات الهوائية الحادة", display: "Acute Bronchitis" },
  {
    value: "K05",
    arDisplay: "التهاب اللثة وأمراض الفم",
    display: "Gingivitis and Oral Diseases",
  },
  {
    value: "K12",
    arDisplay: "التهاب الفم والآفات المرتبطة به",
    display: "Stomatitis and Related Lesions",
  },
  { value: "L03", arDisplay: "التهاب النسيج الخلوي", display: "Cellulitis" },
  { value: "M25", arDisplay: "ألم المفصل", display: "Joint Pain" },
  {
    value: "N41",
    arDisplay: "الأمراض الالتهابية للبروستات",
    display: "Inflammatory Diseases of the Prostate",
  },
  {
    value: "N76",
    arDisplay: "التهابات أخرى في المهبل والفرج",
    display: "Other Vaginal and Vulval Infections",
  },
  {
    value: "O14",
    arDisplay: "ارتفاع ضغط الدم الناتج عن الحمل",
    display: "Pregnancy-Induced Hypertension",
  },
  {
    value: "P01",
    arDisplay: "اضطرابات الوليد المرتبطة بقصر مدة الحمل وانخفاض وزن الولادة",
    display: "Neonatal Disorders Related to Short Gestation and Low Birth Weight",
  },
  { value: "R05", arDisplay: "السعال", display: "Cough" },
  { value: "R55", arDisplay: "الإغماء والانهيار", display: "Syncope and Collapse" },
  { value: "S06", arDisplay: "إصابة داخل الجمجمة", display: "Intracranial Injury" },
  {
    value: "T36",
    arDisplay: "التسمم بالمضادات الحيوية الجهازية",
    display: "Poisoning by Systemic Antibiotics",
  },
  {
    value: "Z73",
    arDisplay: "المشاكل المتعلقة بصعوبة إدارة الحياة",
    display: "Problems Related to Life Management Difficulty",
  },
];

export const immunizationDictionary = [
  { value: "0", arDisplay: "لقاح الإنفلونزا", display: "Influenza Vaccine" },
  {
    value: "1",
    arDisplay: "لقاح الحصبة والنكاف والحصبة الألمانية",
    display: "Measles, Mumps, and Rubella Vaccine",
  },
  { value: "2", arDisplay: "لقاح التهاب الكبد ب", display: "Hepatitis B Vaccine" },
  { value: "3", arDisplay: "لقاح الكزاز", display: "Tetanus Vaccine" },
  { value: "4", arDisplay: "لقاح الدفتيريا", display: "Diphtheria Vaccine" },
  { value: "5", arDisplay: "لقاح السعال الديكي", display: "Pertussis Vaccine" },
  { value: "6", arDisplay: "لقاح شلل الأطفال", display: "Polio Vaccine" },
  { value: "7", arDisplay: "لقاح الالتهاب الرئوي", display: "Pneumonia Vaccine" },
  { value: "8", arDisplay: "لقاح الروتا فيروس", display: "Rotavirus Vaccine" },
  { value: "9", arDisplay: "لقاح جدري الماء", display: "Varicella Vaccine" },
  {
    value: "10",
    arDisplay: "لقاح فيروس الورم الحليمي البشري",
    display: "Human Papillomavirus (HPV) Vaccine",
  },
  { value: "11", arDisplay: "لقاح السحائي", display: "Meningococcal Vaccine" },
  { value: "12", arDisplay: "لقاح التهاب الكبد أ", display: "Hepatitis A Vaccine" },
  {
    value: "13",
    arDisplay: "لقاح هيموفيلوس إنفلونزا ب",
    display: "Haemophilus Influenzae Type B Vaccine",
  },
  { value: "14", arDisplay: "لقاح داء الكلب", display: "Rabies Vaccine" },
  { value: "15", arDisplay: "لقاح التيفوئيد", display: "Typhoid Vaccine" },
  { value: "16", arDisplay: "لقاح الحمى الصفراء", display: "Yellow Fever Vaccine" },
  { value: "17", arDisplay: "لقاح الهربس النطاقي", display: "Herpes Zoster Vaccine" },
  { value: "18", arDisplay: "لقاح السل (بي سي جي)", display: "Tuberculosis (BCG) Vaccine" },
  {
    value: "19",
    arDisplay: "لقاح التهاب الدماغ الياباني",
    display: "Japanese Encephalitis Vaccine",
  },
  { value: "20", arDisplay: "لقاح الكوليرا", display: "Cholera Vaccine" },
  { value: "21", arDisplay: "لقاح داء الكلب", display: "Rabies Vaccine" },
  { value: "22", arDisplay: "لقاح الجمرة الخبيثة", display: "Anthrax Vaccine" },
  { value: "23", arDisplay: "لقاح الجدري", display: "Smallpox Vaccine" },
  { value: "24", arDisplay: "لقاح التيفوس", display: "Typhus Vaccine" },
  { value: "25", arDisplay: "لقاح الملاريا", display: "Malaria Vaccine" },
  { value: "26", arDisplay: "لقاح حمى الضنك", display: "Dengue Fever Vaccine" },
  { value: "27", arDisplay: "لقاح فيروس زيكا", display: "Zika Virus Vaccine" },
  { value: "28", arDisplay: "لقاح الإنفلونزا ب", display: "Influenza B Vaccine" },
  {
    value: "29",
    arDisplay: "لقاح الدمج دي تي بي-هيب ب-هيب",
    display: "DTP-HepB-Hib Combination Vaccine",
  },
  { value: "30", arDisplay: "لقاح شلل الأطفال الفموي", display: "Oral Polio Vaccine" },
  {
    value: "31",
    arDisplay: "لقاح شلل الأطفال غير المُفعل",
    display: "Inactivated Polio Vaccine",
  },
  {
    value: "32",
    arDisplay: "لقاح الحصبة والنكاف والحصبة الألمانية وجدري الماء",
    display: "Measles, Mumps, Rubella, and Varicella Vaccine",
  },
  {
    value: "33",
    arDisplay: "لقاح الدفتيريا والكزاز والسعال الديكي",
    display: "Diphtheria, Tetanus, and Pertussis Vaccine",
  },
  {
    value: "34",
    arDisplay: "لقاح الكزاز والدفتيريا والسعال الديكي",
    display: "Tetanus, Diphtheria, and Pertussis Vaccine",
  },
  {
    value: "35",
    arDisplay: "لقاح إنفلونزا إتش1إن1 (إنفلونزا الخنازير)",
    display: "H1N1 Influenza (Swine Flu) Vaccine",
  },
  { value: "36", arDisplay: "لقاح الإنفلونزا الموسمية", display: "Seasonal Influenza Vaccine" },
  { value: "37", arDisplay: "لقاح الإنفلونزا الأنفي", display: "Nasal Influenza Vaccine" },
  {
    value: "38",
    arDisplay: "لقاح الالتهاب الرئوي البوليسكاريدي للبالغين",
    display: "Pneumococcal Polysaccharide Vaccine for Adults",
  },
  {
    value: "39",
    arDisplay: "لقاح الالتهاب الرئوي المقترن للأطفال",
    display: "Pneumococcal Conjugate Vaccine for Children",
  },
  { value: "40", arDisplay: "لقاح الحزام الناري", display: "Shingles Vaccine" },
  {
    value: "41",
    arDisplay: "لقاح الإنفلونزا الموهن الحي",
    display: "Live Attenuated Influenza Vaccine",
  },
  {
    value: "42",
    arDisplay: "لقاح الإنفلونزا المُعاد تركيبه",
    display: "Recombinant Influenza Vaccine",
  },
  { value: "43", arDisplay: "لقاحات السفر", display: "Travel Vaccines" },
  { value: "44", arDisplay: "لقاح التهاب الكبد س", display: "Hepatitis C Vaccine" },
  {
    value: "45",
    arDisplay: "لقاح إتش بي في 9 (جارداسيل 9)",
    display: "HPV 9 Vaccine (Gardasil 9)",
  },
  { value: "46", arDisplay: "لقاح السحائي ب", display: "Meningococcal B Vaccine" },
  { value: "47", arDisplay: "لقاح السحائي ACWY", display: "Meningococcal ACWY Vaccine" },
  {
    value: "48",
    arDisplay: "لقاح روتا تيك للروتا فيروس",
    display: "Rotarix Rotavirus Vaccine",
  },
  {
    value: "49",
    arDisplay: "لقاح إنفانريكس هيكسا (6 في 1)",
    display: "Infanrix Hexa (6-in-1) Vaccine",
  },
];

export const adverseEventDictionary = [
  { value: "product-problem", arDisplay: "مشكلة في المنتج", display: "Product problem" },
  { value: "product-quality", arDisplay: "جودة المنتج", display: "Product quality" },
  { value: "product-use-error", arDisplay: "خطأ في استخدام المنتج", display: "Product use error" },
  { value: "wrong-dose", arDisplay: "جرعة خاطئة", display: "Wrong dose" },
  {
    value: "incorrect-prescribing-information",
    arDisplay: "معلومات وصفة غير صحيحة",
    display: "Incorrect prescribing information",
  },
  { value: "wrong-technique", arDisplay: "طريقة خاطئة", display: "Wrong technique" },
  {
    value: "wrong-route-of-administration",
    arDisplay: "طريق إعطاء خاطئ",
    display: "Wrong route of administration",
  },
  { value: "wrong-rate", arDisplay: "معدل خاطئ", display: "Wrong rate" },
  { value: "wrong-duration", arDisplay: "مدة خاطئة", display: "Wrong duration" },
  { value: "wrong-time", arDisplay: "وقت خاطئ", display: "Wrong time" },
  { value: "expired-drug", arDisplay: "دواء منتهي الصلاحية", display: "Expired drug" },
  {
    value: "medical-device-use-error",
    arDisplay: "خطأ في استخدام الجهاز الطبي",
    display: "Medical device use error",
  },
  {
    value: "problem-different-manufacturer",
    arDisplay: "مشكلة - شركة مصنّعة مختلفة",
    display: "Problem - different manufacturer",
  },
  {
    value: "unsafe-physical-environment",
    arDisplay: "بيئة مادية غير آمنة",
    display: "Unsafe physical environment",
  },
];
